namespace Hidistro.Entities.Orders
{
	public enum OrderActions
	{
		BUYER_PAY = 1,
		BUYER_CONFIRM_GOODS,
		SELLER_SEND_GOODS = 6,
		SELLER_CONFIRM_PAY,
		SELLER_MODIFY_TRADE,
		SELLER_REJECT_REFUND,
		SELLER_CLOSE,
		MASTER_SELLER_MODIFY_DELIVER_ADDRESS,
		MASTER_SELLER_MODIFY_PAYMENT_MODE,
		MASTER_SELLER_MODIFY_SHIPPING_MODE,
		MASTER_SELLER_MODIFY_GIFTS,
		SELLER_FINISH_TRADE = 0x10,
		CONFIRM_TAKE_GOODS
	}
}
