namespace HiShop.API.HiPOS
{
	public enum Card_UrlNameType
	{
		URL_NAME_TYPE_TAKE_AWAY,
		URL_NAME_TYPE_RESERVATION,
		URL_NAME_TYPE_USE_IMMEDIATELY,
		URL_NAME_TYPE_APPOINTMENT,
		URL_NAME_TYPE_EXCHANGE,
		URL_NAME_TYPE_VEHICLE_INFORMATION
	}
}
