namespace HiShop.API.HiPOS
{
	public enum MemberCard_CustomField_NameType
	{
		FIELD_NAME_TYPE_LEVEL,
		FIELD_NAME_TYPE_COUPON,
		FIELD_NAME_TYPE_STAMP,
		FIELD_NAME_TYPE_DISCOUNT,
		FIELD_NAME_TYPE_ACHIEVEMEN,
		FIELD_NAME_TYPE_MILEAGE
	}
}
